models/user.py
import time

from models.task import Task
# from models import red
from . import ModelMixin
from . import db


class User(db.Model, ModelMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    role = db.Column(db.Integer)
    username = db.Column(db.Text)
    password = db.Column(db.Text)
    avatar = db.Column(db.Text)
    followed = db.Column(db.Text)
    follower = db.Column(db.Text)
    status = db.Column(db.Integer)

    def __init__(self, form):
        self.role = form.get('role', 10)
        self.username = form.get('username', '')
        self.password = form.get('password', '')
        self.followed = form.get('followed', 0)
        self.follower = form.get('follower', 0)
        self.status = form.get('status', 0)
        self.avatar = form.get('avatar', 'default')

    def _update(self, form):
        self.username = form.get('username', self.username)
        self.password = form.get('password', self.password)

    def get_avatar(self):
        if self.avatar == 'default':
            default_path = "/static/img/default.jpg"
            return default_path
        else:
            avatar_path = "/static/img/uploads/" + str(self.id) + "/" + str(self.avatar)
            return avatar_path

    def valid_username(self):
        if User.query.filter_by(username=self.username).first() is None:
            return True
        else:
            return False

    # 验证注册用户的合法性
    def valid(self):
        valid_username = self.valid_username()
        valid_username_len = len(self.username) >= 3
        valid_password_len = len(self.password) >= 3
        msgs = []
        if not valid_username:
            message = '用户名已经存在'
            msgs.append(message)
        if not valid_username_len:
            message = '用户名长度必须大于等于 3'
            msgs.append(message)
        if not valid_password_len:
            message = '密码长度必须大于等于 3'
            msgs.append(message)
        status = valid_username and valid_username_len and valid_password_len
        return status, msgs


def format_time(value):
    format = '%Y-%m-%d %H:%M'
    value = time.localtime(value)
    dt = time.strftime(format, value)
    return dt

routes/user.py
import os

from models.user import User
from routes import *
from utils.utils import log

main = Blueprint('user', __name__)

Model = User

uploads_dir = 'static/img/uploads/'

xfrs_dict = {
    'd40a58205d884331aa7f2a7304ad6345': 0,
}


def current_user():
    uid = session.get('user_id')
    # print('chest init', uid)
    if uid is not None:
        u = User.query.get(uid)
        return u
    else:
        return None


def random_string():
    import uuid
    return str(uuid.uuid4())


@main.route('/')
def index():
    u = current_user()
    if u is not None:
        return redirect(url_for('task.index'))
    ms = Model.query.all()
    xfrs = random_string()
    xfrs_dict[xfrs] = 0
    return render_template('user/index.html', xfrs=xfrs, user_list=ms)


def login_check(func):
    def wrapper(*arg):
        u = current_user()
        if u is None:
            return redirect(url_for('user.index'))
        else:
            print("username", u.username, u.id)
            func(*arg)
            # return func

    return wrapper


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    u = Model(form)
    user = User.query.filter_by(username=u.username).first()
    if user is not None and user.password == u.password:
        session['user_id'] = user.id
        u = current_user()
        u.status = 1
        u.save()
        # print('login successful')
        return redirect(url_for('task.index'))
    else:
        print('login unsuccessful')
        return redirect(url_for('.index'))


@main.route('/edit/<id>')
@login_check
def edit(id):
    m = Model.query.get(id)
    return render_template('user/edit.html', user=m)


@main.route('/quit')
def quit():
    u = current_user()
    u.status = 0
    u.save()
    session.pop('user_id')
    return redirect(url_for('.index'))


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    xfrs = form.get('xfrs')
    print("xfrs", xfrs)
    if xfrs in xfrs_dict:
        xfrs_dict.pop(xfrs)
        u = Model(form)
        status, msgs = u.valid()
        # if (status):
        if status:
            # log("valid", u.valid())
            Model.new(form)
            return redirect(url_for('.index'))
        else:
            return render_template('user/sign_up_again.html', msg=msgs)

    else:
        return 'ERROR LINK'


@main.route('/update/<id>', methods=['POST'])
def update(id):
    form = request.form
    Model.update(id, form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
def delete(id):
    Model.delete(id)
    return redirect(url_for('.index'))


@main.route('/profile/<int:id>')
def profile(id):
    u = current_user()
    return render_template('user/profile.html', user_single=u)


@main.route('/upload/<int:id>', methods=['POST'])
def upload(id):
    print('upload')
    f = request.files.get('uploaded')

    # if f:
    if f:
        filename = f.filename
        print('filename, ', filename)
        import uuid
        filename = str(uuid.uuid4()) + '.' + filename.split('.')[-1]
        temp_dir = uploads_dir + str(id) + '/'
        if not os.path.exists(temp_dir):
            os.mkdir(temp_dir)
        path = temp_dir + filename
        f.save(path)

        u = current_user()
        u.avatar = filename
        u.save()
        return redirect(url_for('.profile', id=id))
    else:
        return redirect(url_for('.profile', id=id))


@main.route('/admin')
def admin():
    u = current_user()
    print("role", u.role)
    if int(u.role) == 1:
        ms = Model.query.all()
        return render_template('user/admin.html', user_list=ms)
    else:
        return '''NO PERMISSION'''

templates/user/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>admin</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>

</head>

<body>

<div class="btn btn-primary btn-sm">

</div>
{% for u in user_list %}


<p class="bg-info " style="font-size:30px">
    <label>id:</label>
    {{ u.id }}
    <label>username:</label>{{ u.username }}  <label>password:</label>{{ u.password }}
    <button class="gua-show-comment btn-primary btn-sm" onClick="location.href='{{ url_for('.edit', id=u.id) }}'">
        修改
    </button>
    <button class="gua-show-comment btn-primary btn-sm" onClick="location.href='{{ url_for('.delete', id=u.id) }}'">
        删除
    </button>
</p>
{% endfor %}
</body>
</html>

templates/user/index.html
<!DOCTYPE html>
<html>

<head>
  <title>MOBAN</title>
  <link href="/static/css/login_style.css" rel='stylesheet' type='text/css' />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="application/x-javascript">
    addEventListener("load", function() {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>
</head>

<body>

  <h1> </h1>

  <div class="app-location">
    <h2>欢迎回来</h2>
    <div class="line"><span></span></div>
    <div class="location"><img src="/static/img/location.png" class="img-responsive" alt="" /></div>
    <form method="post">
      <input class="form-control" type="hidden" name="xfrs" value="{{ xfrs }}">
      <input type="text" class="text" name="username" value="用户名" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '用户名';}">
      <input type="password" name="password" value="Password" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Password';}">
      <div class="submit"><input type="submit" formaction="{{ url_for('.login') }}"     value="登录"></div>
      <div class="submit"><input type="submit" formaction="{{ url_for('.add') }}"    value="注册"></div>
      <div class="clear"></div>
      <div class="new">
        <div class="clear"></div>
      </div>
    </form>
    <text class="footer" style="font-weight:bold;color:white">
       示例帐号:
       用户名:admin
       密码:admin
     </text>
    <p class="footer">
      <text >浙ICP备17027558号</text>
    </p>
  </div>
</body>

</html>


<!--

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>user index</title>
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <style>
    section {
      width: 1000px;
      padding: 10px 10px 10px 500px;
    }

    .footer {
      padding: 25px 30px 40px 30px;
      overflow: auto;

      background: #d4dedf;
      border-top: 1px solid #fff;

      box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.15);
      -moz-box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.15);
      -webkit-box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.15);
    }

    .header {
      padding: 40px 30px 30px 30px;
    }

    .header h1 {
      font-family: 'Bree Serif', serif;
      font-weight: 300;
      font-size: 28px;
      line-height: 34px;
      color: #414848;
      text-shadow: 1px 1px 0 rgba(256, 256, 256, 1.0);
      margin-bottom: 10px;
    }

    #background1 {
      background-image: url(/static/img/backgroundimg.jpg);
      /*background-position: right bottom, left top;*/
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
      /*padding: 15px;*/
    }
  </style>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<div id="background1">

  <body>
    <section>


      <br>
      <div class="header">
        <label>注册</label>
        <form action="{{ url_for('.add') }}" method="post">
          <input class="form-control" type="hidden" name="xfrs" value="{{ xfrs }}">
          <input class="form-control" name="username">
          <br>
          <input class="form-control" name="password">
          <br>
          <button class="btn-primary ">register</button>
        </form>
        <br><br>
        <label>登录</label>
        <form action="{{ url_for('user.login') }}" method="post">
          <input class="form-control" name="username">
          <br>
          <input class="form-control" name="password">
          <br>
          <button class="btn-primary ">login</button>
        </form>
      </div>
      <div>
        <h3 class="footer" style="font-weight:bold;color:white">
         示例帐号:
         用户名:admin
         密码:admin
       </h3>
      </div>
    </section>
  </body>
</div>

</html> -->

templates/user/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>趣推</title>
  <link href="/static/css/style.css" rel="stylesheet" type="text/css"/>
  <script src="/static/js/api.js"></script>
  <script src="/static/js/alertify.min.js"></script>
  <script src="/static/js/jquery-3.0.0.min.js"></script>
  <script src="/static/js/weibo.js"></script>
  <script>
    let log = function() {
      console.log(arguments);
    }
    var upload = function(file) {
      // 要用一个 formdata 对象来装 file
      var fd = new FormData();
      fd.append('uploaded', file);

      log(fd);
      $.ajax({
        url: '/upload',
        method: 'post',
        // 上传文件的时候下面这两个选项一定要加上
        contentType: false,
        processData: false,
        data: fd,
        success: function(r) {
          console.log('上传成功', file.name);
        },
        error: function() {
          console.log('上传失败', file.name);
        }
      });
    };

    $(document).ready(function() {
      $('#id-button-upload').on('click', function() {
        var fileTag = $('#id-input-file')[0];
        var files = fileTag.files;
        var numberOfFiles = files.length;
        if (numberOfFiles == 0) {
          alert('还没有选中文件');
        } else {
          for (var i = 0; i < numberOfFiles; i++) {
            var file = files[i];
            console.log('上传的文件: ', file.name);
            <!--upload(file);-->
          }
        }
      });
    });
  </script>
  <style>
    #background1 {
      background-image: url(/static/img/backgroundimg.jpg);
      /*background-position: right bottom, left top;*/
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
      /*padding: 15px;*/
    }

    .gua-hide {
      display: none;
    }
  </style>
</head>

<body class="post-template-default single single-post postid-576 single-format-standard">
  <div id="page" class="site">
    <div id="background1"  >

    <div class="weibo-container">

      <header role="banner">
        <div class="  masthead-group clearfix container">
          <div>
            <a class="comment-author " href={{ url_for( 'weibo.myweibo', id=user_single.id ) }} title="我的微博">
        <img  id="id-avatar-weibo"  src="/static/img/uploads/{{ user_single.id }}/{{ user_single.avatar }}"  class="img-circle" width="80px" height="80px" alt="我的微博">
        <h1>
        <p id="id-username-weibo">
          {{ user_single.username }}
        </p>
        </h1>
        <h4>war never changes</h4>
        </a>
          </div>

          <nav class="pull-right" role="navigation">
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul id="menu-menu-1" class="nav navbar-nav">
                <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-283">
                  <a style="font-size:20px;color:white" href='{{ url_for('weibo.index') }}'>首页</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-181 current_page_item menu-item-401 active">
                  <a style="font-size:20px;color:white" href='{{ url_for('user.profile', id= user_single.id ) }}'>个人中心</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-402">
                  <a style="font-size:20px;color:white" href='{{ url_for('weibo.myweibo', id= user_single.id ) }}'>我的微博</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-403">
                  <a style="font-size:20px;color:white" href='{{ url_for('weibo.mycollect' ) }}'>收藏</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-403">
                  <a style="font-size:20px;color:white" href='{{ url_for('weibo.followed' ) }}'>关注</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-403">
                  <a style="font-size:20px;color:white" href='{{ url_for('user.quit' ) }}'>退出</a></li>
              </ul>
            </div>
          </nav>
        </div>
      </header>




      <div id="container" class="container">
        <div id="primary" style="margin-bottom: 230px;" class="row right_side">


          <div id="content" role="main" class="image-comment-on col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <div class="entry-container box clearfix  ">


              <div>
                <img src="/static/img/uploads/{{ user_single.id }}/{{ user_single.avatar }}" class="img-circle" width="110px" height="110" />
                <br><br>
                <form action="{{ url_for('.upload', id=user_single.id) }}" method="post" enctype=multipart/form-data>
                  <label>
          <input type="file" name="uploaded">
      </label>
                  <br>
                  <button type="submit" class="btn btn-primary btn-sm">
       上传头像
      </button>
                </form>
              </div>

              <div>
                <p>
                  <h3>用户id:</h3> {{ user_single.id }} <br>
                  <h3>用户名:</h3> {{ user_single.username }} <br>
                  <br>
                  <button class="btn btn-primary btn-sm" onClick="location.href='{{ url_for('.edit', id=user_single.id) }}'">修改用户名</button>
                  <button class="btn btn-primary btn-sm" onClick="location.href='{{ url_for('weibo.index') }}'">返回微博</button>

                </p>
                <br><br>





              </div>

            </div>
          </div>
        </div>


      </div>
    </div>
        </div>
    <script>
      document.getElementById("upfile").value = Math.random().toString(36).substr(2);
    </script>
</body>

</html>

templates/user/sign_up_again.html
<!DOCTYPE html>
<html>

<head>
  <title>MOBAN</title>
  <link href="/static/css/login_style.css" rel='stylesheet' type='text/css' />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body>

  <h1> </h1>

  <div class="app-location">
    <h2>{{msg}}</h2>
    <div class="line"><span></span></div>
    <div class="location"><img src="/static/img/location.png" class="img-responsive" alt="" /></div>

  </div>
</body>

</html>